### ISSUE TITLE
Incorrect stoploss setting leading to Emergency Exit

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#10460]
## Description:
There appears to be an issue with the calculation of unrealized profit, which is resulting in an emergency exit with an incorrect profit/loss percentage. The strategy logs show an unrealized profit of -89.99%, which is inconsistent with the provided open rate and current rate.
## Logs:
![image](https://github.com/user-attachments/assets/5809d999-1c86-4bbb-81fb-7c37d69fb5db)
```yaml
❌ Binance: Exiting WLD/USDT (#2)
Unrealized Profit: -89.99% (loss: -180.036 USDT / -180.036 USD)
Exit Reason: emergency_exit
Direction: Long
Amount: 98.8
Open Rate: 2.023 USDT
Current Rate: 2.025 USDT
Exit Rate: 0.203 USDT
Duration: 0:00:14 (0.2 min)

```
## Expected Behavior:
The unrealized profit should reflect the actual profit/loss based on the difference between the open rate and the current rate, not an exaggerated -89.99%.

## Environment:
I use dokcer: freqtradeorg/freqtrade:stable
