### ISSUE TITLE
Docker: RTX 3090 not detected but GTX 1080 is detected

### ISSUE THREAD

**Issue by ajunca** [freqtrade/freqtrade#10743]
Hi,

I'm using torch on my strategy and running on docker. The problem arise because I have to graphics card, and one is detected and the other not. It detects my older GTX 1080 but not the newer RTX 3090. Other docker instances not related to freqtrade can use it both with no problem (with the same docker compose configuration), so it is not a problem on this configuration. I tried several ways, just passing one, by id, passing all... Always the same result, can use the GTX 1080 but not the RTX 3090. I'm using a custom Docker file and tried to pip install different versions of torch with the same result. Also tried to derive the dockerfile from stable and develop with same result. My last dockerfile configuration and docker compose are the followings (but I tried multiple different):

```
FROM freqtradeorg/freqtrade:develop

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
USER root

RUN apt-get update && apt-get install -y git python3-pip python3-dev python3-opencv

# Switch back to user (only if you required root above)
USER ftuser

RUN python3 -m pip install --upgrade pip
RUN pip3 install --user torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
RUN pip3 install --user plotly
RUN pip3 install --user git+https://github.com/amazon-science/chronos-forecasting.git
RUN pip3 install diskcache
```

```
services:
  freqtrade:
    image: freqtrade_custom
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1', '0']
              capabilities: [gpu]
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./models:/freqtrade/user_data/models"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config_futures.json
      --strategy ChronosStrategy
```

Any idea on what is happening?
