### ISSUE TITLE
Unable to Access Freqtrade Web UI from Host Despite Binding to 0.0.0.0 in Docker Configuration

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#10869]
## Describe your environment

  * Operating system: __ubuntu 22.04__
  * Python Version: __latest docker___ (`python -V`)
  * CCXT version: ___latest docker__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __latest docker__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

I am trying to access the Freqtrade Web UI running in a Docker container from my host machine. I have configured the application to bind to 0.0.0.0 in both the config and docker-compose files, but I am still unable to access the Web UI from the host. However, I can successfully access the Freqtrade Web UI when running curl http://localhost:8080 from within the container itself. It seems that the service is correctly listening on the expected port, but external access from the host machine is blocked or not reaching the container.

### Steps to reproduce:

  1. docker-compose up -d
  2.
 ```sh
root@hcss-ecs-8e6f:~/freqtrade# curl http://127.0.0.1:8080
curl: (56) Recv failure: Connection reset by peer
root@hcss-ecs-8e6f:~/freqtrade# docker exec -it freqtrade /bin/bash
ftuser@0ca29fd79795:/freqtrade$ curl http://127.0.0.1:8080
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
 ```
  
 
### Observed Results:

  * What happened?
  can't access frequi
  * What did you expect to happen?
  access frequi
### Relevant code exceptions or logs
my docker-compose.yml:
```yml
---
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data:rw"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy example_strategy

```
