### ISSUE TITLE
Unable to Access the Freqtrade Web UI with docker

### ISSUE THREAD

**Issue by HughLK** [freqtrade/freqtrade#10993]
## Describe your environment

  * Operating system:  **Ubuntu 20.04.2**
  * Python Version: **3.12.7** (`python -V`)
  * CCXT version: **4.4.24(**`pip freeze | grep ccxt`)
  * Freqtrade Version: **2024.10** (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
i ran Freqtrade docker binding to 0.0.0.0 in both the config.json and docker-compose files.
When I tried to access the Freqtrade Web UI, it got error:
``` bash
root@vm:/home/ft_userdata# curl http://localhost:8080
curl: (56) Recv failure: Connection reset by peer
```

So I got into the docker and tried again, still got error:
```bash
root@vm:/home/ft_userdata# docker exec -it freqtrade /bin/bash
ftuser@1f285f4bcbb6:/freqtrade$ curl http://localhost:8080
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
```

Here's my docker-compose.yml:
```yml
---
version: '3.0'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```
