### ISSUE TITLE
Invalid configuration. Reason: '["BTC/USDT", "ETH/USDT"]' is not of type 'array'

### ISSUE THREAD

**Issue by danipolo** [freqtrade/freqtrade#11161]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3
  
## Describe the problem:

Environment variable:
- FREQTRADE__EXCHANGE__PAIR_WHITELIST=["BTC/USDT", "ETH/USDT"]

When I'm passing the pairs through env instead of the config file, It's returning me this error:

freqtrade.configuration.config_validation - INFO - Validating configuration ...
freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. Reason: '["BTC/USDT", "ETH/USDT"]' is not of type 'array'

### Steps to reproduce:

  1. Pass the pairs through env variable FREQTRADE__EXCHANGE__PAIR_WHITELIST=["BTC/USDT", "ETH/USDT"]
  2. Run the bot
  3. Returns this error
  
### Observed Results:

  * What happened?
 
It seems that it's understanding the array as a string

  * What did you expect to happen?

Be passed as an array

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
version: '3.8'
services:
  freqtrade-bot:
    image: ${FREQTRADE__IMAGE}
    restart: always
    container_name: ${FREQTRADE__BOT_NAME}
    mem_limit: 1g
    mem_reservation: 1g
    cpus: 1
    volumes:
      - "/opt/freqtrade-bots/user_data:/freqtrade/user_data"
    ports:
      - "0.0.0.0:${FREQTRADE__PORT}:8080"
    environment:
      - TZ=Europe/Andorra
      - FREQTRADE__DRY_RUN=${FREQTRADE__DRY_RUN}
      - FREQTRADE__BOT_NAME=${FREQTRADE__BOT_NAME}
      - FREQTRADE__PORT=${FREQTRADE__PORT}
      - FREQTRADE__STRATEGY=${FREQTRADE__STRATEGY}
      - FREQTRADE__IMAGE=${FREQTRADE__IMAGE}
      - FREQTRADE__CONFIG_JSON=${FREQTRADE__CONFIG_JSON}
      - FREQTRADE__TELEGRAM__TOKEN=${FREQTRADE__TELEGRAM__TOKEN}
      - FREQTRADE__TELEGRAM__CHAT_ID=${FREQTRADE__TELEGRAM__CHAT_ID}
      - FREQTRADE__EXCHANGE__NAME=${FREQTRADE__EXCHANGE__NAME}
      - FREQTRADE__EXCHANGE__KEY=${FREQTRADE__EXCHANGE__KEY}
      - FREQTRADE__EXCHANGE__SECRET=${FREQTRADE__EXCHANGE__SECRET}
      - FREQTRADE__EXCHANGE__PAIR_WHITELIST=${FREQTRADE__EXCHANGE__PAIR_WHITELIST}
  ```

Error:
```
024-12-30 03:17:20,150 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. Reason: '["BTC/USDT", "ETH/USDT"]' is not of type 'array'

Failed validating 'type' in schema['properties']['exchange']['properties']['pair_whitelist']:

    {'description': 'List of whitelisted trading pairs.',

     'type': 'array',

     'items': {'type': 'string'},

     'uniqueItems': True}

On instance['exchange']['pair_whitelist']:

    '["BTC/USDT", "ETH/USDT"]'

2024-12-30 03:17:20,151 - freqtrade - ERROR - Fatal exception!
```
