### ISSUE TITLE
How to Enable the Backtesting Option in FreqUI When Running Freqtrade via Docker on Windows 10?

### ISSUE THREAD

**Issue by ray147291617** [freqtrade/freqtrade#11511]
Hello Freqtrade community,

Could I kindly ask a beginner question? I’m running Freqtrade using Docker on Windows 10 and noticed in the documentation that FreqUI includes backtesting functionality. However, when I access FreqUI, I only see the options "Trade," "Dashboard," and "Chart Logs." Could you please guide me on how to enable or access the backtesting feature in FreqUI?
Any advice would be greatly appreciated! Thank you in advance for your help!
OS: Windows 10
Installation: Docker-based Freqtrade

**Comment by xmatthias** [comment]
You will want to start the bot in [webserver mode](https://www.freqtrade.io/en/latest/utils/#webserver-mode).

the simplest way will be to update the `command` section to webserver (and your config) - and then run `docker compose up` - which will enable the backtesting tab.

**Comment by ray147291617** [comment]
🙏Thank you so much.the backtesting tab is visible

**Comment by x0y-gt** [comment]
I'm unable to see the backtesting tab, in each tab just shows the FreqUI modal to connect to a bot, I have this docker-compose:

```
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      webserver
      -c /freqtrade/user_data/config.json
      -d /freqtrade/user_data/backtest_results
      --userdir /freqtrade/user_data
```

Am I doing something wrong?
