### ISSUE TITLE
How can i configure persistent logs with docker volumes?

### ISSUE THREAD

**Issue by cwirz** [freqtrade/freqtrade#11709]
I'm trying to make logs persistent in a docker volume and it gives me permission denied for new docker volumes it creates

```yml
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    build:
      context: .
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "logs:/freqtrade/user_data/logs"
      - "database:/freqtrade/user_data/database"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/database/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MyStrategy

volumes:
  logs:
  database:
```

```
freqtrade  | 2025-05-03 22:15:13,784 - freqtrade - INFO - freqtrade 2025.4
freqtrade  | 2025-05-03 22:15:14,508 - numexpr.utils - INFO - NumExpr defaulting to 10 threads.
freqtrade  | 2025-05-03 22:15:16,778 - freqtrade.worker - INFO - Starting worker 2025.4
freqtrade  | 2025-05-03 22:15:16,778 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade  | 2025-05-03 22:15:16,782 - freqtrade - ERROR - Fatal exception!
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/usr/local/lib/python3.12/logging/config.py", line 608, in configure
freqtrade  |     handler = self.configure_handler(handlers[name])
freqtrade  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/usr/local/lib/python3.12/logging/config.py", line 876, in configure_handler
freqtrade  |     result = factory(**kwargs)
freqtrade  |              ^^^^^^^^^^^^^^^^^
freqtrade  |   File "/usr/local/lib/python3.12/logging/handlers.py", line 155, in __init__
freqtrade  |     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
freqtrade  |   File "/usr/local/lib/python3.12/logging/handlers.py", line 58, in __init__
freqtrade  |     logging.FileHandler.__init__(self, filename, mode=mode,
freqtrade  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1231, in __init__
freqtrade  |     StreamHandler.__init__(self, self._open())
freqtrade  |                                  ^^^^^^^^^^^^
freqtrade  |   File "/usr/local/lib/python3.12/logging/__init__.py", line 1263, in _open
freqtrade  |     return open_func(self.baseFilename, self.mode,
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  | PermissionError: [Errno 13] Permission denied: '/freqtrade/user_data/logs/freqtrade.log'
freqtrade  | 
freqtrade  | The above exception was the direct cause of the following exception:
freqtrade  | 
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/main.py", line 47, in main
freqtrade  |     return_code = args["func"](args)
freqtrade  |                   ^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
freqtrade  |     worker = Worker(args)
freqtrade  |              ^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 39, in __init__
freqtrade  |     self._init(False)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade  |     self._config = Configuration(self._args, None).get_config()
freqtrade  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 52, in get_config
freqtrade  |     self.config = self.load_config()
freqtrade  |                   ^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 97, in load_config
freqtrade  |     self._process_logging_options(config)
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 147, in _process_logging_options
freqtrade  |     setup_logging(config)
freqtrade  |   File "/freqtrade/freqtrade/loggers/__init__.py", line 215, in setup_logging
freqtrade  |     logging.config.dictConfig(log_config)
freqtrade  |   File "/usr/local/lib/python3.12/logging/config.py", line 942, in dictConfig
freqtrade  |     dictConfigClass(config).configure()
freqtrade  |   File "/usr/local/lib/python3.12/logging/config.py", line 615, in configure
freqtrade  |     raise ValueError('Unable to configure handler '
freqtrade  | ValueError: Unable to configure handler 'file'

```

Any idea how to make this work? I dont want to keep the logs in the user data folder since i have the content of this folder checked in my repo and version controlled for CI/CD.
