### ISSUE TITLE
hyperopt got ChildProcessError inside docker

### ISSUE THREAD

**Issue by futuretech6** [freqtrade/freqtrade#11844]
## Describe your environment

Operating System:	Linux-6.8.0-47-generic-x86_64-with-glibc2.36
Python Version:		Python 3.12.10
CCXT Version:		4.4.77

Freqtrade Version:	freqtrade 2025.4

## Describe the problem:

I got an error inside docker:

```
Exception ignored in: <function ResourceTracker.__del__ at 0x7f3c91da7600>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/local/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/local/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
```

But hyperopt works fine **outside** docker.

I have tried setting `pid=host`, `ipc=shared`, `shm_size=1g`, but without any changes.

### Steps to reproduce:

```bash
docker compose run --rm \
  freqtrade hyperopt -j-2 -e100 \
  --hyperopt-loss SharpeHyperOptLossDaily \
  --timerange=$(date -d "10 month ago" +%Y%m%d)-$(date +%Y%m%d) \
  --strategy test \
  --spaces roi stoploss trailing buy sell
```
  
### Observed Results:

  * What happened: as described above.
  * What did you expect to happen: exit gracefully

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

my compose.yaml:

```yaml
services:
  freqtrade:
    container_name: freqtrade
    # image: freqtrade-custom
    build:
      context: .
      dockerfile: "Dockerfile.custom"
      # network: host
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    network_mode: host
    pid: host
    ipc: "shareable"
    shm_size: '1g'
    volumes: ["./user_data:/freqtrade/user_data"]
    command: >
      trade
        --db-url sqlite:////freqtrade/user_data/db/tradesv3.sqlite
        --logfile /freqtrade/user_data/logs/trade.log
        --strategy test
```

my dockerfile.custom:

```dockerfile
FROM freqtradeorg/freqtrade:stable

ARG TARGETOS
ARG TARGETARCH
ARG UID
ARG GID

USER root

COPY chid.sh /chid.sh
RUN chmod +x /chid.sh
RUN /chid.sh  # chown /freqtrade

USER ftuser
```
