### ISSUE TITLE
docker-compose for jupyter lab?

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#3559]
## Describe your environment

  * Operating system: Linux rescuer 4.15.0-108-generic #109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  * Python Version: Python 3.6.9
  * CCXT version: 1.30.48 
  * Freqtrade Version: 2020.6
  
I am very new to docker, so I am following the [docker-compose installation guide](https://www.freqtrade.io/en/latest/docker/#freqtrade-with-docker-compose). 
Now I am also trying to follow the [backtest analysis guide](https://www.freqtrade.io/en/latest/data-analysis/), but it doesn't cover the docker-compose user case. How do I do jupyter notebook analysis with docker-compose?

**Comment by xmatthias** [comment]
the prebuilt docker-image is mainly designed for production runs (trade / dry-run). Backtesting and hyperopt works too - although hyperopt has some (memory) limitations.

Jupyter is not installed in the image, mainly for image size reasons - and keeping an image small is beneficial when you plan to run the bot for weeks or months at a time.

You can however create a dockerfile similar to `Dockerfile.technical` - install jupyter (lab / notebook) there - and expose the port jupyter starts up (usually 8888) via the compose file.

The compose would then look similar to the following:

```yaml
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:master
    # image: freqtradeorg/freqtrade:develop
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./Dockerfile.jupyter"
    restart: unless-stopped
    container_name: freqtrade
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    entrypoint: jupyter lab

```

One thing to point out: as this compose-file uses a different entrypoint (jupyter, instead of freqtrade) you will not be able to run freqtrade with this compose file, so best keep both this and the other file around.

* typos in the above are included - and `Dockerfile.jupyter` is referenced above, but not provided by freqtrade.
