### ISSUE TITLE
2nd telegram chat user

### ISSUE THREAD

**Issue by mschultheiss83** [freqtrade/freqtrade#3572]
## Describe your environment

  * Operating system: Win10
  * Python Version: 3.8.3 (`python -V`)
  * CCXT version: 1.30.64 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
**how can i get a 2nd chat user in the docker version?**

**first attempt** - edit files / add new local branch / merge every update
i added "chat_id2" with the id in "user_data/config.json"
i updated (edited) telegram.py to use a 2nd chat user like this [telegram.py](https://gist.github.com/mschultheiss83/3e97229eb027255adccff157f65f15f4)
but if i try to add in docker-compose.yml under **volumes**:
```
- "./freqtrade/rpc:/freqtrade/freqtrade/rpc"
```
it breaks... like this:
```
freqtrade    | Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/main.py", line 36, in main
freqtrade    |     return_code = args['func'](args)
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 14, in start_trading
freqtrade    |     from freqtrade.worker import Worker
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 15, in <module>
freqtrade    |     from freqtrade.freqtradebot import FreqtradeBot
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 27, in <module>
freqtrade    |     from freqtrade.rpc import RPCManager, RPCMessageType
freqtrade    |   File "/freqtrade/freqtrade/rpc/__init__.py", line 1, in <module>
freqtrade    |     from .rpc import RPC, RPCMessageType, RPCException  # noqa
freqtrade    |   File "/freqtrade/freqtrade/rpc/rpc.py", line 14, in <module>
freqtrade    |     from freqtrade.exceptions import ExchangeError, PricingError
freqtrade    | ImportError: cannot import name 'ExchangeError' from 'freqtrade.exceptions' (/freqtrade/freqtrade/exceptions.py)
```
**second attempt** - this should be the better way // move local file into the image on start up
so i don't know docker that well plus i don't want to mess with new local git branch an merge all the time, 
**so is there a better way?**

something like to 
use a file stored locally under "user_data/rpc/telegram.py" and 
move it on start up (docker-compose up) into the image on the right position
"/freqtrade/freqtrade/rpc/telegram.py" 
if i did get it right

**Comment by mschultheiss83** [comment]
sorry, i did a mistake, the error in **first attempt** was from a not updated (container) image

**Comment by mschultheiss83** [comment]
[update]

**Comment by xmatthias** [comment]
well what would you need a 2nd telegram user for? 

Will that then send to both users, and both users can control the bot?

**Comment by mschultheiss83** [comment]
@xmatthias 
i run this "project" with my brother, and sure, your code is great. 
this is just a little update, you can test it, with my id 😃

so i just updated the docker-compose to
```yml
---
version: '3'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:master
    image: freqtradeorg/freqtrade:develop   #<< ** use dev branch **
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./freqtrade/rpc:/freqtrade/freqtrade/rpc"
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MySuperStrategy
```

and replaced the `freqtrade/rpc/telegram.py` from [here](https://gist.github.com/mschultheiss83/3e97229eb027255adccff157f65f15f4)
