### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml'

### ISSUE THREAD

**Issue by manvalorian** [freqtrade/freqtrade#4226]
## Describe your environment

  * Operating system: Ubuntu Mate
  * Python Version: 3.9.0 (`python -V`)
  * CCXT version: N/A (`pip freeze | grep ccxt`)
  * Freqtrade Version: N/A (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

At trying to build the freqtrade build with technical indicators as descriped in the manual, I encountered following problem:

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.freqtrade:'context'
service.freqtrade.build contains an invalid type, it should be a string, or an object

 image: freqtrade_custom
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.freqtrade:'context'
service.freqtrade.build contains an invalid type, it should be a string, or an object

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Most likely, it's an indentation problem.

You should provide us with the full compose file - that way we can test it out (make sure to remove eventual secrets, although a compose file should not contain any).

Please wrap it in tripple-ticks ` - as formatting of this file is important.

**Comment by manvalorian** [comment]
---
version: '3'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable_pi
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    image: freqtrade_custom
    build:
    context: .
    dockerfile: "./docker/Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy

**Comment by manvalorian** [comment]
```
---
version: '3'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable_pi
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    image: freqtrade_custom
    build:
    context: .
    dockerfile: "./docker/Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```

**Comment by xmatthias** [comment]
the correct version will indent context and docker-file into the "build" key:

```yaml
---
version: '3'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable_pi
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    image: freqtrade_custom
    build:
      context: .
      dockerfile: "./docker/Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```
