### ISSUE TITLE
permission denied on freqtrade.log after update to 2021.4

### ISSUE THREAD

**Issue by klara31** [freqtrade/freqtrade#4839]
## Describe your environment

  * Operating system: Linux running docker
  * Freqtrade Version: 2021.4
  
## Describe the problem:

After updating the docker container to freqtrade 2021.4, freqtrade does not start anymore. Logs show a permission denied error on freqtrade.log. My docker-compose has not changed and was working on 2021.3 without problems.

### Relevant code exceptions or logs

  ```
freqtrade       | 2021-04-30 09:18:18,123 - freqtrade.worker - INFO - Starting worker 2021.4
freqtrade       | 2021-04-30 09:18:18,123 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade       | 2021-04-30 09:18:18,124 - freqtrade.commands.trade_commands - ERROR - [Errno 13] Permission denied: '/freqtrade/user_data/logs/freqtrade.log'
freqtrade       | 2021-04-30 09:18:18,124 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade       | Traceback (most recent call last):
freqtrade       |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade       |     worker = Worker(args)
freqtrade       |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade       |     self._init(False)
freqtrade       |   File "/freqtrade/freqtrade/worker.py", line 49, in _init
freqtrade       |     self._config = Configuration(self._args, None).get_config()
freqtrade       |   File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
freqtrade       |     self.config = self.load_config()
freqtrade       |   File "/freqtrade/freqtrade/configuration/configuration.py", line 97, in load_config
freqtrade       |     self._process_logging_options(config)
freqtrade       |   File "/freqtrade/freqtrade/configuration/configuration.py", line 131, in _process_logging_options
freqtrade       |     setup_logging(config)
freqtrade       |   File "/freqtrade/freqtrade/loggers.py", line 109, in setup_logging
freqtrade       |     handler_rf = RotatingFileHandler(logfile,
freqtrade       |   File "/usr/local/lib/python3.9/logging/handlers.py", line 153, in __init__
freqtrade       |     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
freqtrade       |   File "/usr/local/lib/python3.9/logging/handlers.py", line 58, in __init__
freqtrade       |     logging.FileHandler.__init__(self, filename, mode=mode,
freqtrade       |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1146, in __init__
freqtrade       |     StreamHandler.__init__(self, self._open())
freqtrade       |   File "/usr/local/lib/python3.9/logging/__init__.py", line 1175, in _open
freqtrade       |     return open(self.baseFilename, self.mode, encoding=self.encoding,
freqtrade       | PermissionError: [Errno 13] Permission denied: '/freqtrade/user_data/logs/freqtrade.log'

  ```

My docker-compose.yml:
```
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    network_mode: bridge
    ports:
      - 8080:8080
    volumes:
      - ${USERDIR}/freqtrade:/freqtrade/user_data
      - /etc/localtime:/etc/localtime:ro
    # Default command used when running `docker compose up` 
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy xxxxxl

```
