### ISSUE TITLE
Docker Custom file

### ISSUE THREAD

**Issue by lulu-angry** [freqtrade/freqtrade#5376]
## Describe your environment

  * Operating system: ____Ubuntu
  * Python Version: _____  3.8
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ Last
  
## Your question

Hello there,
I come here to help, i tried to install Pandas_ta in my docker.
but when i docker-compose up -d
docker return me this : The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.freqtrade: 'dockerfile'
services.freqtrade.build contains an invalid type, it should be a string, or an object

 here is my docker file : 
```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
    context: .
    dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_TQ
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    # ports:
    #   - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config_BNCE.json
      --strategy CoreV1
```
and my custom : 

 pip install pandas_ta

**Comment by xmatthias** [comment]
as the error states (kindof, if you know what to look for), your indentation is wrong.

you'll need to indent the lines below "build" for this to work..

```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_TQ
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    # ports:
    #   - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config_BNCE.json
      --strategy CoreV1
```

your custom should also be using `pip install --user <whatever module` - so you're not loading modules from multiple places (which can lead to odd problems).
