### ISSUE TITLE
TA-lib dependency installation failing when building freqtrade image with Docker

### ISSUE THREAD

**Issue by peacefulbadger** [freqtrade/freqtrade#5591]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5 (conda) 
  * CCXT version: 1.45.44
  * Freqtrade Version: freqtrade docker-9c50d0c2 (Docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Attempting to build freqtrade and dependencies as a Docker image. `docker-compose build` on either stable or development images both fail when `RUN pip3 install freqtrade` is ran due to an issue installing TA-lib dependency. Removing `RUN pip3 install freqtrade` results in a successful build. 

### Steps to reproduce:

  1. `docker-compose pull` with this docker-compose file: 

```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --strategy NostalgiaForInfinityNext
      --config /freqtrade/user_data/config.json
      --dry-run  
```
  2. `docker-compose build` with this Docker.custom file:

```
# FROM freqtradeorg/freqtrade:develop
FROM freqtradeorg/freqtrade:stable

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
USER root

# COPY --chown=1000:1000  tests/requirements.txt /freqtrade

RUN apt-get update
RUN apt-get install -y python3-dev

RUN pip3 install wheel
RUN pip3 install freqtrade
RUN pip3 install pandas-ta
RUN pip3 install pytest
RUN pip3 install pytest-mock
RUN pip3 install pytest-subtests

# RUN pip install --no-cache-dir --no-build-isolation -r /freqtrade/requirements.txt
```

 
### Observed Results:

  * What happened? 

Failure when attempting to install dependency TA-lib

  * What did you expect to happen?

Build of an image with freqtrade

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.
```
#8 38.34 Building wheels for collected packages: py-find-1st, sdnotify, TA-Lib, wrapt
#8 38.35   Building wheel for py-find-1st (PEP 517): started
#8 39.08   Building wheel for py-find-1st (PEP 517): finished with status 'error'
#8 39.08   ERROR: Command errored out with exit status 1:
#8 39.08    command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp0tkjqn30    
#8 39.08        cwd: /tmp/pip-install-qnuvxm7j/py-find-1st_b014c2c7cd8744b095af5f46c908ba6e
#8 39.08   Complete output (19 lines):
#8 39.08   /tmp/pip-build-env-8ho6n5v8/overlay/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
#8 39.08     warnings.warn(
#8 39.08   running bdist_wheel
#8 39.08   running build
#8 39.08   running build_py
#8 39.08   creating build
#8 39.08   creating build/lib.linux-x86_64-3.9
#8 39.08   creating build/lib.linux-x86_64-3.9/utils_find_1st
#8 39.08   copying utils_find_1st/__init__.py -> build/lib.linux-x86_64-3.9/utils_find_1st
#8 39.08   warning: build_py: byte-compiling is disabled, skipping.
#8 39.08
#8 39.08   running build_ext
#8 39.08   check for clang compiler ... compiler test call failed with error 2 msg: No such file or directory
#8 39.08   no
#8 39.08   building 'find_1st' extension
#8 39.08   creating build/temp.linux-x86_64-3.9
#8 39.08   creating build/temp.linux-x86_64-3.9/utils_find_1st
#8 39.08   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -I/tmp/pip-build-env-8ho6n5v8/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/local/include/python3.9 -c utils_find_1st/find_1st.cpp -o build/temp.linux-x86_64-3.9/utils_find_1st/find_1st.o
#8 39.08   error: command 'gcc' failed: No such file or directory
#8 39.08   ----------------------------------------
#8 39.08   ERROR: Failed building wheel for py-find-1st
#8 39.08   Building wheel for sdnotify (setup.py): started
#8 39.80   Building wheel for sdnotify (setup.py): finished with status 'done'
#8 39.80   Created wheel for sdnotify: filename=sdnotify-0.3.2-py3-none-any.whl size=3231 sha256=39547be674387d8d1ed1fb49c46d95df352cc8ccf6155c519b553cf34030f914
#8 39.80   Stored in directory: /root/.cache/pip/wheels/5d/34/b6/c06c0b2fa404bd83b1897c06b9dd13c72387482d70a40ef65d
#8 39.81   Building wheel for TA-Lib (setup.py): started
#8 40.76   Building wheel for TA-Lib (setup.py): finished with status 'error'
#8 40.76   ERROR: Command errored out with exit status 1:
#8 40.76    command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qnuvxm7j/ta-lib_58d86131d7494c10b08c71b8e14f838f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qnuvxm7j/ta-lib_58d86131d7494c10b08c71b8e14f838f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pfifz57r
#8 40.76        cwd: /tmp/pip-install-qnuvxm7j/ta-lib_58d86131d7494c10b08c71b8e14f838f/
#8 40.76   Complete output (23 lines):
#8 40.76   running bdist_wheel
#8 40.76   running build
#8 40.76   running build_py
#8 40.76   creating build
#8 40.76   creating build/lib.linux-x86_64-3.9
#8 40.76   creating build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/test_func.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/test_pandas.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/stream.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/abstract.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/deprecated.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/test_abstract.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/test_stream.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/test_data.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   copying talib/__init__.py -> build/lib.linux-x86_64-3.9/talib
#8 40.76   warning: build_py: byte-compiling is disabled, skipping.
#8 40.76   
#8 40.76   running build_ext
#8 40.76   building 'talib._ta_lib' extension
#8 40.76   creating build/temp.linux-x86_64-3.9
#8 40.76   creating build/temp.linux-x86_64-3.9/talib
#8 40.76   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-install-qnuvxm7j/ta-lib_58d86131d7494c10b08c71b8e14f838f/.eggs/numpy-1.21.2-py3.9-linux-x86_64.egg/numpy/core/include -I/usr/local/include/python3.9 -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.9/talib/_ta_lib.o
#8 40.76   error: command 'gcc' failed: No such file or directory
#8 40.76   ----------------------------------------
#8 40.76   ERROR: Failed building wheel for TA-Lib
#8 40.76   Running setup.py clean for TA-Lib
#8 41.32   Building wheel for wrapt (setup.py): started
#8 42.08   Building wheel for wrapt (setup.py): finished with status 'done'
#8 42.08   Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19572 sha256=3680c7641789198f8853724e4bc3c8bd14679fd3514ea53ff26868eab02c3e5d  
#8 42.08   Stored in directory: /root/.cache/pip/wheels/98/23/68/efe259aaca055e93b08e74fbe512819c69a2155c11ba3c0f10
#8 42.08 Successfully built sdnotify wrapt
#8 42.08 Failed to build py-find-1st TA-Lib
#8 42.08 ERROR: Could not build wheels for py-find-1st which use PEP 517 and cannot be installed directly
```
