### ISSUE TITLE
When deploy with docker-compose and traefik for SSL, I can't connect

### ISSUE THREAD

**Issue by mpaya5** [freqtrade/freqtrade#8625]
## Describe your environment

  * Operating system:  Ubuntu 22.04
  * Python Version: _____ python3.10.10
  * CCXT version: _____ 3.0.37
  * Freqtrade Version: ____ freqtrade:latest
  
## Describe the problem:

In a private server I have installed traefik and portainer correctly using docker-compose.
I also have deplyed a freqUI using this docker-compose.yml:

```
---
version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  frequi-dev:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: frequi
    # image: freqtradeorg/frequi:main
    restart: unless-stopped
    ports:
      - "3000:80"
    labels:
      - traefik.http.routers.frequi-dev.rule=Host(`${FREQUI_DOMAIN}`)
      - traefik.http.routers.frequi-dev.tls=true
      - traefik.http.routers.frequi-dev.tls.certresolver=lets-encrypt
      - traefik.port=3000
    networks:
      - internal
      - web
```

This FreqUI is running correctly. Let's say **FREQUI_DOMAIN** = `frequi.example.com`. So if I go to `https://frequi.example.com`  is working perfectly.

Then I have a freqtrade webserver running with this docker-compose.yml:
*(I have created an image using freqtrade called freqtrade_main)*
```
---
version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  freqtrade-dev:
    image: localhost:5000/freqtrade_main
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      webserver
      --config /freqtrade/user_data/config.json
    restart: unless-stopped
    labels:
      - traefik.http.routers.freqtrade-dev.rule=Host(`${WEBSERVER_DOMAIN}`)
      - traefik.http.routers.freqtrade-dev.tls=true
      - traefik.http.routers.freqtrade-dev.tls.certresolver=lets-encrypt
      - traefik.http.services.freqtrade-dev.loadbalancer.server.port=8080
    networks:
      - web
      - internal

```
Let's say WEBSERVER_DOMAIN is webserver.example.com and if I go to `https://webserver.example.com` is working perfectly
And the config file of the webserver freqtrade is:
```
....
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "somerandompassword",
        "ws_token": "somerandomwstoken",
        "CORS_origins": [
            "https://frequi.example.com"
        ],
        "username": "*******",
        "password": "********"

```

I don't know why but is impossible to connect from `https://frequi.example.com` to ` https://webserver.example.com`
 And both bots are running correctly and without a problem
