### ISSUE TITLE
A number of trades immediately exit after entering with duration:0 on 1 min strategy backtesting.

### ISSUE THREAD

**Issue by zhaohui-yang** [freqtrade/freqtrade#9016]
## Describe your environment

  * Operating system: _Linux 18.04___
  * Python Version: __python 3.10.9___ (`python -V`)
  * CCXT version: __ccxt==3.1.44___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2023.6.dev-a90b7c0bf__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

A number of trades immediately exit after entering with duration 0 on 1 min strategy backtesting.

For example:
```python
>>> pprint(mat['strategy']['SampleStrategy']['trades'][5])
{'amount': 9.301,
 'close_date': '2023-05-01 00:02:00+00:00',
 'close_rate': 117.5,
 'close_timestamp': 1682899320000,
 'enter_tag': None,
 'exit_reason': 'trailing_stop_loss',
 'fee_close': 0.0002,
 'fee_open': 0.0002,
 'initial_stop_loss_abs': 117.66,
 'initial_stop_loss_ratio': -0.03,
 'is_open': False,
 'is_short': True,
 'leverage': 20.0,
 'max_rate': 117.5,
 'max_stake_amount': 1092.77449,
 'min_rate': 117.33,
 'open_date': '2023-05-01 00:02:00+00:00',
 'open_rate': 117.49,
 'open_timestamp': 1682899320000,
 'orders': [{'amount': 9.301,
             'ft_is_entry': True,
             'ft_order_side': 'sell',
             'order_filled_timestamp': 1682899320000,
             'safe_price': 117.49},
            {'amount': 9.301,
             'ft_is_entry': False,
             'ft_order_side': 'buy',
             'order_filled_timestamp': 1682899320000,
             'safe_price': 117.5}],
 'pair': 'BCH/USDT:USDT',
 'profit_abs': -0.5301384,
 'profit_ratio': -0.009704553935730656,
 'stake_amount': 54.6387245,
 'stop_loss_abs': 117.5,
 'stop_loss_ratio': -0.03,
 'trade_duration': 0}
```

In this one minite bar, the OHLC is (117.49, 117.5, 117.33, 117.5). With leverage 20.0, the initial_stop_loss_abs is set to 117.66. It seems that this trade will not exit till the next bar. However, it closed.

```yaml
{
  "timeframe": "1m",
  "trailing_stop": true,
  "trailing_only_offset_is_reached": false,


  "max_open_trades": 18,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "dry_run": true,
  "db_url": "sqlite:///tradesv3.dryrun.sqlite",
  "dry_run_wallet": 1000,
  "cancel_open_orders_on_exit": false,
  "trading_mode": "futures",
  "margin_mode": "isolated",
  "unfilledtimeout": {
    "entry": 10,
    "exit": 10,
    "exit_timeout_count": 0,
    "unit": "minutes"
  },
  "minimal_roi": {
    "1440": -1
  },
  "use_exit_signal": false,
  "use_custom_stoploss": false,
  "order_types": {
    "entry": "market", 
    "exit": "market", 
    "emergency_exit": "market",
    "force_exit": "market", // entry from Telegram
    "force_entry": "market", // exit from Telegram
    "stoploss": "market",
    "stoploss_price_type": "last",
    "stoploss_on_exchange": true
  },
  "entry_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1,
    "price_last_balance": 0.0,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "exit_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1
  },
```

My questions are:
1. What is the exact enter price in one bar, open/max/min/close?
2. Why this order immediate exit after entering?

Thanks.
