### ISSUE TITLE
How can I freqtrade and jupyter lab together?

### ISSUE THREAD

**Issue by AliM1988** [freqtrade/freqtrade#9689]
I use freqtrade (develop_plot) without issue. 
Also, I can use Jupyter Lab by your [docker-compose](https://github.com/freqtrade/freqtrade/blob/develop/docker/docker-compose-jupyter.yml) and [Dockerfile ](https://github.com/freqtrade/freqtrade/blob/develop/docker/Dockerfile.jupyter) without issue.

Now, I want build a new image that Freqtrade and JupyterLab run at same time and handled with a single container. I need your advice, this idea is good or not. Also, please help me to do it for complete test. 

I created new image with below docker-compose and [Dockerfile .jupyter](https://github.com/freqtrade/freqtrade/blob/develop/docker/Dockerfile.jupyter) :
```
version: '3'
services:
  freqtrade:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    restart: unless-stopped
    container_name: freqtrade-jupyterlab

    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8888:8888"  # Port for JupyterLab
      - "127.0.0.1:8000:8080"  # Port for Freqtrade API & FreqUI
    # Default command used when running `docker compose up`
    command: >
      sh -c "freqtrade trade --logfile /freqtrade/user_data/logs/freqtrade.log --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite --config /freqtrade/user_data/config.json --strategy SampleStrategy & jupyter lab --port=8888 --ip 0.0.0.0 --allow-root --NotebookApp.token=''"
```
      
---------------------
The result:
- The Telegram bot ran.
- Jupyter Lab worked fine.
- FreqUI worked.
- Other commands of freqtrade didn't work. see below

command:

`docker-compose run --rm freqtrade -h`

error:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-h": executable file not found in $PATH: unknown
```
